import { Timestamp } from "firebase/firestore";

export type ActionStatus = "pending" | "verified" | "rejected";
export type ActorType = "individual" | "organization" | "government" | "ngo";

export interface Action {
    id: string;
    registryId: string;
    institutionId: string | null;
    actionType: string;
    quantity: number;
    unit: string;
    address: string;
    lat: number | null;
    lng: number | null;
    userId: string;
    userEmail: string;
    actorType: ActorType;
    actorName: string;
    contactPerson: string;
    phone: string;
    email: string;
    status: ActionStatus;
    sector?: string;
    state?: string;
    pincode?: string;
    co2eKg: number | null;
    atmanirbharPercent: number | null;
    circularityPercent: number | null;
    wasteGeneratedKg: number | null;
    wasteDivertedKg: number | null;
    sha256Hash: string;
    meterPhotos: string[];
    sitePhoto: string | null;
    energyBillCopy?: string | null;
    meterPhoto?: string | null;
    moreDetailsPhoto?: string | null;
    siteOverviewPhoto?: string | null;
    commissioningDate: string | null;
    localPercent: number | null;
    indigenousPercent: number | null;
    communityPercent: number | null;
    jobsCreated: number | null;
    razorpayOrderId: string | null;
    razorpayPaymentId: string | null;
    verifiedAt?: string | null;
    verifiedBy?: string | null;
    adminNotes?: string | null;
    calculationVersion?: string | null;
    calculationMethodology?: string | null;
    emissionFactorUsed?: string | null;
    baselineEnergyGrid?: number | null;
    baselineEnergyDiesel?: number | null;
    baselineEnergySolar?: number | null;
    baselineWaterMunicipal?: number | null;
    baselineWaterRain?: number | null;
    baselineWaterWaste?: number | null;
    baselineWasteOrganic?: number | null;
    baselineWasteInorganic?: number | null;
    baselineWasteHazardous?: number | null;
    studentsCount?: number | null;
    createdAt: Timestamp;
    updatedAt?: Timestamp;
}

export interface ActionFormData {
    actionType: string;
    quantity: number | string;
    unit: string;
    address: string;
    lat: number | null;
    lng: number | null;
    actorType: ActorType;
    actorName: string;
    contactPerson: string;
    phone: string;
    email: string;
    meterPhotos: string[];
    sitePhoto: string | null;
    energyBillCopy?: string | null;
    meterPhoto?: string | null;
    moreDetailsPhoto?: string | null;
    siteOverviewPhoto?: string | null;
    photo_file?: any;
    commissioningDate: string;
    localPercent: number | string;
    indigenousPercent: number | string;
    communityPercent: number | string;
    jobsCreated: number | string;
    wasteGeneratedKg: number | string;
    wasteDivertedKg: number | string;
    baselineEnergyGrid: number | string;
    baselineEnergyDiesel: number | string;
    baselineEnergySolar: number | string;
    baselineWaterMunicipal: number | string;
    baselineWaterRain: number | string;
    baselineWaterWaste: number | string;
    baselineWasteOrganic: number | string;
    baselineWasteInorganic: number | string;
    baselineWasteHazardous: number | string;
    studentsCount: number | string;
    consentGiven: boolean;
    disclaimerAccepted: boolean;
}
